
import { BrowserRouter, Link, Route, Switch } from "react-router-dom";

function CycleGAN() {
    return (
        <div id="contents">
            <div className="clearfix">
                <div className="sidebar">
                    <div>
                        <h2>Practices</h2>
                        <ul>
                            <li>
                                <Link to="/gan/sketch">Pix2Pix GAN</Link>
                            </li>

                            <li>
                                <Link to="/gan/colorgan">Color GAN</Link>
                            </li>
                            <li>
                                <Link to="/gan/dcgan">DC GAN</Link>
                            </li>
                            <li>
                                <Link to="/gan/cycle">Cycle GAN</Link>
                            </li>
                        </ul>
                    </div>
                </div>
                <div className="main">
                    <h1>CYCLE GAN</h1>
                    <h2>Monet To Photo</h2>
                    <br />
                    <div class="">
                        <div class="box">
                            <img src="/images/cycle.png" alt="Img" height="300" width="584" />
                        </div>
                    </div>
                    <h4>About Cycle GAN</h4>
                    <p>
                        Above are the images generated by our CYCLE GAN.Image-to-image translation involves
                        generating a new synthetic version of a given image with a specific modification, such as
                        translating a summer landscape to winter.
                    </p>
                    <p>
                        Training a model for image-to-image translation typically requires a large dataset of
                        paired examples. These datasets can be difficult and expensive to prepare, and in some cases
                        impossible, such as photographs of paintings by long dead artists.
                    </p>
                    <p>
                        The CycleGAN is a technique that involves the automatic training of image-to-image translation models
                        without paired examples. The models are trained in an unsupervised manner using a collection of images
                        from the source and target domain that do not need to be related in any way.
                    </p>
                    <h4>Note Book</h4>
                    <a
                        target="_blank"
                        href="https://drive.google.com/file/d/1BY7iQxRuyiMixxzX83jaACyQQqr8Ox_F/view?usp=sharing"
                        className="subscribe">
                        Download Notebook
                    </a>
                </div>
            </div>
        </div>
    );
}

export default CycleGAN;